CoSmellRefine/Models/ViewModels/RepositoryContent.cs
using System.Text.Json.Serialization;

namespace CoSmellRefine.Models.ViewModels
{
    public class RepositoryContent
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("path")]
        public string Path { get; set; }

        [JsonPropertyName("sha")]
        public string Sha { get; set; }

        [JsonPropertyName("url")]
        public string Url { get; set; }

        [JsonPropertyName("git_url")]
        public string GitUrl { get; set; }

        [JsonPropertyName("html_url")]
        public string HtmlUrl { get; set; }

        [JsonPropertyName("download_url")]
        public string DownloadUrl { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("_links")]
        public Links Links { get; set; }
    }

    public class Links
    {
        [JsonPropertyName("self")]
        public string Self { get; set; }

        [JsonPropertyName("git")]
        public string Git { get; set; }

        [JsonPropertyName("html")]
        public string Html { get; set; }
    }
}

CoSmellRefine/Controllers/GitHubRepositoryController.cs
using CoSmellRefine.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Caching.Memory;
using System.Net.Http.Headers;
using System.Text.Json;

namespace CoSmellRefine.Controllers
{
    [Authorize]
    public class GitHubRepositoryController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHttpClientFactory _clientFactory;
        private readonly IDistributedCache _distributedCache;
        public GitHubRepositoryController(UserManager<IdentityUser> userManager, IHttpClientFactory clientFactory, IDistributedCache distributedCache)
        {
            this._userManager = userManager;    
            this._clientFactory = clientFactory;   
            this._distributedCache = distributedCache;
            
        }
        public async Task<IActionResult> Repositories()
        {
            var user = await _userManager.GetUserAsync(User);
            var claims = await _userManager.GetClaimsAsync(user);
            var accessToken = claims.FirstOrDefault(c => c.Type == "access_token")?.Value;
            if (accessToken == null)
            {
                TempData["error"] = "You have to login through GitHub to use this feature";
                return View("LoginPrompt");
            }
            var cacheKey = $"repositories_{user.Id}";
            var cachedRepositories = await _distributedCache.GetStringAsync(cacheKey);
            List<Repository> repositories;

            if (!string.IsNullOrEmpty(cachedRepositories))
            {
                repositories = JsonSerializer.Deserialize<List<Repository>>(cachedRepositories);
            }
            else
            {
                var client = _clientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                client.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("CoSmellRefine", "1.0"));

                var response = await client.GetStringAsync("https://api.github.com/user/repos");
                repositories = JsonSerializer.Deserialize<List<Repository>>(response);

                // Set cache options
                var cacheEntryOptions = new DistributedCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(5)) // Sliding expiration
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(10)); // Absolute expiration

                // Cache the data
                var serializedRepositories = JsonSerializer.Serialize(repositories);
                await _distributedCache.SetStringAsync(cacheKey, serializedRepositories, cacheEntryOptions);
            }

            return View(repositories);
        }

        public async Task<IActionResult> RepositoryContent(string owner, string repo, string path = "")
        {
            var user = await _userManager.GetUserAsync(User);
            var claims = await _userManager.GetClaimsAsync(user);
            var accessToken = claims.FirstOrDefault(c => c.Type == "access_token")?.Value;

            if (accessToken == null)
            {
                return RedirectToAction(nameof(AccountController.Login), "Account");
            }

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            client.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("CoSmellRefine", "1.0"));

            var url = $"https://api.github.com/repos/{owner}/{repo}/contents/{path}";
            var response = await client.GetStringAsync(url);
            var contents = JsonSerializer.Deserialize<List<RepositoryContent>>(response);

            ViewData["Owner"] = owner;
            ViewData["Repo"] = repo;

            return View(contents);
        }

        public async Task<IActionResult> RepositoryFileContent(string owner, string repo, string path)
        {
            var user = await _userManager.GetUserAsync(User);
            var claims = await _userManager.GetClaimsAsync(user);
            var accessToken = claims.FirstOrDefault(c => c.Type == "access_token")?.Value;

            if (accessToken == null)
            {
                return RedirectToAction(nameof(AccountController.Login), "Account");
            }

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            client.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("CoSmellRefine", "1.0"));

            var url = $"https://api.github.com/repos/{owner}/{repo}/contents/{path}";
            var response = await client.GetStringAsync(url);
            var contentData = JsonSerializer.Deserialize<RepositoryContent>(response);

            if (contentData.Type == "file" && contentData.DownloadUrl != null)
            {
                var fileResponse = await client.GetStringAsync(contentData.DownloadUrl);
                ViewData["FileName"] = contentData.Name;
                ViewData["FileContent"] = fileResponse;
                ViewData["Owner"] = owner;
                ViewData["Repo"] = repo;
                return View("FileContent");
            }

            return RedirectToAction(nameof(RepositoryContent), new { owner, repo, path });
        }

    }
}

CoSmellRefine/Views/GitHubRepository/FileContent.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
}

<div class="container mt-5">
    <a asp-controller="GitHubRepository" asp-action="RepositoryContent" asp-route-owner='@ViewData["Owner"]' asp-route-repo='@ViewData["Repo"]' class="btn dark-btn mb-5">
        <i class="fas fa-arrow-left"></i> Back
    </a>

    <h2 class="m-0">File: @ViewData["FileName"]</h2>
    <div class="card mt-2">
        <div class="card-body">
            <div class="d-flex justify-content-end align-items-center">
                <button class="btn btn-outline-dark copy-btn" data-clipboard-target="#fileContent">
                    <i class="bi bi-clipboard"></i> Copy
                </button>
            </div>
           
            <pre id="fileContent">@ViewData["FileContent"]</pre>
        </div>
               
    </div>

</div>


@section Scripts {
    <script>
        new ClipboardJS('.copy-btn');
    </script>
}

CoSmellRefine/Views/GitHubRepository/LoginPrompt.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "GitHub Login Required";
}

<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="text-center">
        <h2>GitHub Login Required</h2>
        <p>To use this feature, you need to log in via your GitHub account.</p>
        <form asp-controller="Account" asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
            <button type="submit" name="provider" value="GitHub" class="btn light-btn d-flex justify-content-center align-items-center w-100">
                <img src="/images/github-logo.svg" alt="GitHub Logo" style="height: 24px; margin-right: 8px;">
                <span>Continue with GitHub</span>
            </button>
        </form>
    </div>
</div>




@section Scripts {
    <script>
        new ClipboardJS('.copy-btn');
    </script>
}

CoSmellRefine/Views/GitHubRepository/Repositories.cshtml
@model List<CoSmellRefine.Models.ViewModels.Repository>
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
}


<div class="container mt-5">
    <p class="h2">Your Repositories</p>
    <div class="card">
        <ul class="list-group list-group-flush">
                @foreach (var repo in Model)
                {
                    <li class="list-group-item">
                        <a asp-action="RepositoryContent" asp-route-owner="@repo.full_name.Split('/')[0]" asp-route-repo="@repo.name">@repo.name</a>
                    </li>
                }
        </ul>
    </div>
</div>

CoSmellRefine/Views/GitHubRepository/RepositoryContent.cshtml
@model List<CoSmellRefine.Models.ViewModels.RepositoryContent>
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
}


<div class="container mt-5">
    <a asp-controller="GitHubRepository" asp-action="Repositories" class="btn dark-btn mb-5">
        <i class="fas fa-arrow-left"></i> Back
    </a>
    <p class="h2 m-0">Repository Contents</p>

            <div class="card">
                <ul class="list-group list-group-flush">
            @foreach (var content in Model)
            {
                <li class="list-group-item">
                    @if (content.Type == "dir")
                    {
                        <a asp-action="RepositoryContent" asp-route-owner="@ViewData["Owner"]" asp-route-repo="@ViewData["Repo"]" asp-route-path="@content.Path">@content.Name</a>
                    }
                    else if (content.Type == "file")
                    {
                        <a asp-action="RepositoryFileContent" asp-route-owner="@ViewData["Owner"]" asp-route-repo="@ViewData["Repo"]" asp-route-path="@content.Path">@content.Name</a>
                    }
                </li>
            }
                </ul>
            </div>
</div>