CoSmellRefine/Controllers/ModeratorIssueController.cs
using CoSmellRefine.Hubs;
using CoSmellRefine.Models.Domain;
using CoSmellRefine.Models.ViewModels;
using CoSmellRefine.Repositories;
using CoSmellRefine.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace CoSmellRefine.Controllers
{
    [Authorize]
    public class ModeratorIssueController : Controller
    {
        private readonly IReportIssueRepository reportIssueRepository;
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IQuestionRepository questionRepository;
        private readonly IQuestionResponseRepository questionResponseRepository;
        private readonly IResponseCommentRepository responseCommentRepository;
        private readonly INotificationRepository notificationRepository;
        private readonly IHubContext<QuestionHub> questionHub;

        public ModeratorIssueController(IReportIssueRepository reportIssueRepository,
            UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, IQuestionRepository questionRepository, IQuestionResponseRepository questionResponseRepository, IResponseCommentRepository responseCommentRepository, INotificationRepository notificationRepository, IHubContext<QuestionHub> questionHub)
        {
            this.reportIssueRepository = reportIssueRepository;
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.questionRepository = questionRepository;
            this.questionResponseRepository = questionResponseRepository;
            this.responseCommentRepository = responseCommentRepository;
            this.notificationRepository = notificationRepository;
            this.questionHub = questionHub;
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List(
              string? searchQuery,
              string? sortBy,
              string? sortDirection,
              int pageSize = 3,
              int pageNumber = 1)
        {
            var totalRecords = await reportIssueRepository.CountAsync();
            var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

            if (pageNumber > totalPages)
            {
                pageNumber--;
            }

            if (pageNumber < 1)
            {
                pageNumber++;
            }

            ViewBag.TotalPages = totalPages;
            ViewBag.SearchQuery = searchQuery;
            ViewBag.SortBy = sortBy;
            ViewBag.SortDirection = sortDirection;
            ViewBag.PageSize = pageSize;
            ViewBag.PageNumber = pageNumber;

            var reportIssueList = await reportIssueRepository.GetAllAsync(searchQuery, sortBy, sortDirection, pageNumber, pageSize);
            return View(reportIssueList);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            // Retrieve the result from the repository
            var issue = await reportIssueRepository.GetAsync(id);

            if (issue != null)
            {
                // map the domain model into the view model
                var model = new ReportIssueDetails
                {
                    Id = issue.Id,
                    User = issue.User,
                    DiscussionItemId = issue.DiscussionItemId,
                    Reason = issue.Reason,
                    ReportDate = issue.ReportDate,
                    Status = issue.Status,
                    StatusReason = issue.StatusReason,
                    DiscussionType = issue.DiscussionType
                };
                return View(model);
            }

            // pass data to view
            return View(null);

        }


        [HttpPost]
        public async Task<IActionResult> WarnUser(ReportIssueDetails issueDetails)
        {
            var reportIssue = await reportIssueRepository.GetAsync(issueDetails.Id);
            DateTime utcNow = DateTime.UtcNow;
            TimeZoneInfo malaysiaZone = TimeZoneInfo.FindSystemTimeZoneById("Singapore Standard Time");
            DateTime malaysiaTime = TimeZoneInfo.ConvertTimeFromUtc(utcNow, malaysiaZone);
            if (reportIssue != null)
            {
                reportIssue.Status = ReportIssueStatus.WarnedUser;
                reportIssue.StatusReason = issueDetails.StatusReason;

                string userId = null;

                // Get the respective content based on the Type attribute and extract the user ID
                switch (issueDetails.DiscussionType)
                {
                    case DiscussionType.Question:
                        var question = questionRepository.Get(issueDetails.DiscussionItemId);
                        if (question != null)
                        {
                            userId = question.UserId;
                        }
                        break;
                    case DiscussionType.Response:
                        var questionResponse = questionResponseRepository.Get(issueDetails.DiscussionItemId);
                        if (questionResponse != null)
                        {
                            userId = questionResponse.UserId;
                        }
                        break;
                    case DiscussionType.ResponseComment:
                        var responseComment = responseCommentRepository.Get(issueDetails.DiscussionItemId);
                        if (responseComment != null)
                        {
                            userId = responseComment.UserId;
                        }
                        break;
                    default:
                        throw new InvalidOperationException("Unknown issue type.");
                }

                if (userId != null)
                {
                    // Create and send the notification
                    var notification = new Notification
                    {
                        Id = Guid.NewGuid(),
                        UserId = userId,
                        Message = "You have been warned due to inappropriate content.",
                        SentTime = malaysiaTime,
                        IsRead = false
                    };

                    notificationRepository.Add(notification);
                }



                //update the issue
                var updatedIssue = await reportIssueRepository.UpdateAsync(reportIssue);
                if (updatedIssue != null)
                {
                    // Show success notification
                    TempData["success"] = "The user has been successfully warned";
                    return RedirectToAction("List");
                }

            }
            TempData["error"] = "Failed to warn the user";
            return RedirectToAction("Details", new { id = issueDetails.Id });

        }

        [HttpPost]
        public async Task<IActionResult> RemoveContent(ReportIssueDetails issueDetails)
        {
            var reportIssue = await reportIssueRepository.GetAsync(issueDetails.Id);
            if (reportIssue != null)
            {
                reportIssue.Status = ReportIssueStatus.ContentRemoved;
                reportIssue.StatusReason = issueDetails.StatusReason;
                //remove the content
                switch (issueDetails.DiscussionType)
                {
                    case DiscussionType.Question:
                        await questionRepository.DeleteAsync(issueDetails.DiscussionItemId);
                        await questionHub.Clients.All.SendAsync("ContentRemoved", issueDetails.DiscussionItemId, "Question");
                        break;
                    case DiscussionType.Response:
                        await questionResponseRepository.DeleteAsync(issueDetails.DiscussionItemId);
                        await questionHub.Clients.All.SendAsync("ContentRemoved", issueDetails.DiscussionItemId, "Response");
                        break;
                    case DiscussionType.ResponseComment:
                        await responseCommentRepository.DeleteAsync(issueDetails.DiscussionItemId);
                        await questionHub.Clients.All.SendAsync("ContentRemoved", issueDetails.DiscussionItemId, "ResponseComment");
                        break;
                    default:
                        // Handle unknown type or throw an exception
                        throw new InvalidOperationException("Unknown issue type.");
                }

                var updatedIssue = await reportIssueRepository.UpdateAsync(reportIssue);
                if (updatedIssue != null)
                {
                    // Show success notification
                    TempData["success"] = "The content has been successfully removed";
                    return RedirectToAction("List");
                }

            }
            TempData["error"] = "Failed to remove the content";
            return RedirectToAction("Details", new { id = issueDetails.Id });

        }

        [HttpPost]
        public async Task<IActionResult> NoActionNeeded(ReportIssueDetails issueDetails)
        {
            var reportIssue = await reportIssueRepository.GetAsync(issueDetails.Id);
            if (reportIssue != null)
            {
                reportIssue.Status = ReportIssueStatus.NoActionNeeded;
                reportIssue.StatusReason = issueDetails.StatusReason;
                var updatedIssue = await reportIssueRepository.UpdateAsync(reportIssue);
                if (updatedIssue != null)
                {
                    // Show success notification
                    TempData["success"] = "The issue has been succesfully updated";
                    return RedirectToAction("List");
                }

            }

CoSmellRefine/Views/ModeratorIssue/Details.cshtml
@model CoSmellRefine.Models.ViewModels.ReportIssueDetails
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
}


<div class="py-2">
    <div class="container">
        <a asp-controller="ModeratorIssue" asp-action="List" class="btn dark-btn mb-5">
            <i class="fas fa-arrow-left"></i> Back
        </a>
        <h1>Reported Issue Details</h1>
    </div>
</div>
<div class="d-flex flex-row justify-content-end me-3">
    <a class="btn dark-btn" asp-controller="ModeratorIssue" asp-action="ViewReferencedItem" asp-route-discussionItemId="@Model.DiscussionItemId" asp-route-discussionType="@Model.DiscussionType">
        View Referenced Item <i class="fas fa-external-link-alt"></i>
    </a>
</div>

<div class="container py-5">
    @if (Model != null)
    {
        <form method="post">
            <div class="mb-3">
                <label class="form-label">Id</label>
                <input type="text" class="form-control" id="id" asp-for="Id" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">User</label>
                <input type="text" class="form-control" id="user" asp-for="@Model.User.UserName" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">Reason</label>
                <input type="text" class="form-control" id="reason" asp-for="Reason" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">Reported Date</label>
                <input type="date" class="form-control" id="reportDate" asp-for="ReportDate" readonly />
            </div>
            <div class="mb-3">
                <label class="form-label">Discussion Type</label>
                <input type="text" class="form-control" id="discussionType" asp-for="DiscussionType" readonly />

            </div>
            <div class="mb-3">
                <label class="form-label">Status</label>
                <input type="text" class="form-control" id="status" asp-for="Status" readonly />
            </div>

            @if (Model.Status.Equals(CoSmellRefine.Utility.ReportIssueStatus.InReview))
            {
                <div class="mt-5 mb-3 d-flex">
                    <button type="button" class="btn btn-warning me-2" data-bs-toggle="modal" data-bs-target="#warnUserModal">
                        <i class="fas fa-exclamation-circle"></i> Warn User
                    </button>

                    <button type="button" class="btn btn-danger me-2" data-bs-toggle="modal" data-bs-target="#removeContent">
                        <i class="fas fa-trash-alt"></i> Remove Content
                    </button>

                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#noActionNeeded">
                        <i class="fas fa-check-circle"></i> No Action Needed
                    </button>
                </div>
                        
            }
      


        </form>
    }

    else
    {
        <p>No blog post found!</p>

    }
</div>
<form method="post" asp-action="WarnUser">
    <div class="modal fade" id="warnUserModal" tabindex="-1" aria-labelledby="warnUserModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="warnUserModalLabel">Please Provide Reason</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" asp-for="DiscussionItemId" hidden />
                    <input type="text" class="form-control" asp-for="DiscussionType" hidden />
                    <div class="mb-3">
                        <label class="form-label">Id</label>
                        <input type="text" class="form-control" id="id" asp-for="Id" readonly />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Reason</label>
                        <input type="text" class="form-control" asp-for="StatusReason" required />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-action="RemoveContent">
    <div class="modal fade" id="removeContent" tabindex="-1" aria-labelledby="removeContent" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="removeContentLabel">Please Provide Reason</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" asp-for="DiscussionItemId" hidden />
                    <input type="text" class="form-control" asp-for="DiscussionType" hidden />
                    <div class="mb-3">
                        <label class="form-label">Id</label>
                        <input type="text" class="form-control" id="id" asp-for="Id" readonly />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Reason</label>
                        <input type="text" class="form-control" asp-for="StatusReason" required />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" asp-action="NoActionNeeded">
    <div class="modal fade" id="noActionNeeded" tabindex="-1" aria-labelledby="noActionNeeded" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="noActionNeededLabel">Please Provide Reason</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" asp-for="DiscussionItemId" hidden />
                    <input type="text" class="form-control" asp-for="DiscussionType" hidden />
                    <div class="mb-3">
                        <label class="form-label">Id</label>
                        <input type="text" class="form-control" id="id" asp-for="Id" readonly />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Reason</label>
                        <input type="text" class="form-control" asp-for="StatusReason" required />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>

CoSmellRefine/Views/ModeratorIssue/List.cshtml
@model List<CoSmellRefine.Models.Domain.ReportIssue>
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
    int nextPage = Convert.ToInt32(ViewBag.PageNumber) + 1;
    int prevPage = Convert.ToInt32(ViewBag.PageNumber) - 1;
}


<div class="py-2">
    <div class="container">
        <h1>Reported Issues</h1>
    </div>
</div>
<form method="get"
        asp-controller="ModeratorIssue" ,
        asp-action="List">
    <div class="container mt-5">
        <div class="row">
            <div class="col col-md-3 d-flex">
                <input type="text" class="form-control"
                        name="searchQuery" value="@ViewBag.SearchQuery" />
                <button type="submit" class="btn btn-warning ms-3">Search</button>
            </div>
        </div>
    </div>
</form>
<div class="">
    <div class="container py-5">
        @if (Model != null && Model.Any())
        {
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>
                                <div class="d-flex flex-row justify-content-center align-items-center">
                                    User
                                    <span>
                                        <a class="btn btn-link"
                                            asp-controller="ModeratorIssue"
                                            asp-action="List"
                                            asp-route-sortBy="User"
                                            asp-route-sortDirection="Asc"
                                            asp-route-searchQuery="@ViewBag.SearchQuery">
                                            <i class="bi bi-arrow-up"></i>
                                        </a>
                                    </span>
                                    <span>
                                        <a class="btn btn-link"
                                            asp-controller="ModeratorIssue"
                                            asp-action="List"
                                            asp-route-sortBy="User"
                                            asp-route-sortDirection="Desc"
                                            asp-route-searchQuery="@ViewBag.SearchQuery">
                                            <i class="bi bi-arrow-down"></i>
                                        </a>
                                    </span>
                                </div>
                            </th>
                            <th>
                                <div class="d-flex flex-row justify-content-center align-items-center">
                                    Report Date
                                    <span>
                                        <a class="btn btn-link"
                                            asp-controller="ModeratorIssue"
                                            asp-action="List"
                                            asp-route-sortBy="ReportDate"
                                            asp-route-sortDirection="Asc"
                                            asp-route-searchQuery="@ViewBag.SearchQuery">
                                            <i class="bi bi-arrow-up"></i>
                                        </a>
                                    </span>
                                    <span>
                                        <a class="btn btn-link"
                                            asp-controller="ModeratorIssue"
                                            asp-action="List"
                                            asp-route-sortBy="ReportDate"
                                            asp-route-sortDirection="Desc"
                                            asp-route-searchQuery="@ViewBag.SearchQuery">
                                            <i class="bi bi-arrow-down"></i>
                                        </a>
                                    </span>
                                </div>
                            </th>
                            <th>
                                <div class="d-flex flex-row justify-content-center align-items-center">
                                    Status
                                    <span>
                                        <a class="btn btn-link"
                                            asp-controller="ModeratorIssue"
                                            asp-action="List"
                                            asp-route-sortBy="Status"
                                            asp-route-sortDirection="Asc"
                                            asp-route-searchQuery="@ViewBag.SearchQuery">
                                            <i class="bi bi-arrow-up"></i>
                                        </a>
                                    </span>
                                    <span>
                                        <a class="btn btn-link"
                                            asp-controller="ModeratorIssue"
                                            asp-action="List"
                                            asp-route-sortBy="Status"
                                            asp-route-sortDirection="Desc"
                                            asp-route-searchQuery="@ViewBag.SearchQuery">
                                            <i class="bi bi-arrow-down"></i>
                                        </a>
                                    </span>
                                </div>
                            </th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var issue in Model)
                        {
                            <tr>
                                <td>@issue.Id</td>
                                <td>@issue.User.UserName</td>
                                <td>@issue.ReportDate</td>
                                <td>@issue.Status</td>
                                <td>
                                    <a asp-controller="ModeratorIssue" asp-action="Details" asp-route-id="@issue.Id" class="btn btn-primary mx-2">
                                        <i class="bi bi-eye-fill"></i> Review
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
                 
            <nav aria-label="Page navigation example" class="bg-transparent mt-5 d-flex justify-content-center">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link"
                            asp-controller="ModeratorIssue"
                            asp-action="List"
                            asp-route-pageNumber="@prevPage"
                            asp-route-pageSize="@ViewBag.PageSize"
                            asp-route-sortBy="@ViewBag.SortBy"
                            asp-route-sortDirection="@ViewBag.SortDirection">
                            Previous
                        </a>
                    </li>

                    @for (int i = 1; i <= ViewBag.TotalPages; i++)
                    {
                        <li class="page-item">
                            <a class="page-link"
                                asp-controller="ModeratorIssue"
                                asp-action="List"
                                asp-route-pageNumber="@i"
                                asp-route-pageSize="@ViewBag.PageSize"
                                asp-route-sortBy="@ViewBag.SortBy"
                                asp-route-sortDirection="@ViewBag.SortDirection">
                                @i
                            </a>
                        </li>
                    }


                    <li class="page-item">
                        <a class="page-link"
                            asp-controller="ModeratorIssue"
                            asp-action="List"
                            asp-route-pageNumber="@nextPage"
                            asp-route-pageSize="@ViewBag.PageSize"
                            asp-route-sortBy="@ViewBag.SortBy"
                            asp-route-sortDirection="@ViewBag.SortDirection">
                            Next
                        </a>
                    </li>
                </ul>
            </nav>
        }
        else
        {
            <p>No discussion found!</p>
        }
    </div>
</div>