CoSmellRefine/Controllers/DeveloperQuestionController.cs
using CoSmellRefine.Hubs;
using CoSmellRefine.Models.Domain;
using CoSmellRefine.Models.ViewModels;
using CoSmellRefine.Repositories;
using CoSmellRefine.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Text.Json;

namespace CoSmellRefine.Controllers
{
    [Authorize]
    public class DeveloperQuestionController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly ICodeSmellRepository codeSmellRepository;
        private readonly IQuestionRepository questionRepository;
        private readonly IQuestionResponseRepository questionResponseRepository;
        private readonly IResponseCommentRepository responseCommentRepository;
        private readonly IReportIssueRepository reportIssueRepository;
        private readonly IRefactoringTechniqueRepository refactoringTechniqueRepository;
        private readonly IVoteRepository voteRepository;
        private readonly IHttpClientFactory _clientFactory;
        private readonly IHubContext<QuestionHub> questionHub;
        private readonly INotificationRepository notificationRepository;
        private readonly IMemoryCache memoryCache;

        public DeveloperQuestionController(ICodeSmellRepository codeSmellRepository, IQuestionRepository questionRepository, UserManager<IdentityUser> userManager, IQuestionResponseRepository questionResponseRepository, IResponseCommentRepository responseCommentRepository, IReportIssueRepository reportIssueRepository, IRefactoringTechniqueRepository refactoringTechniqueRepository, IVoteRepository voteRepository, IHttpClientFactory clientFactory, IHubContext<QuestionHub> questionHub, IMemoryCache memoryCache, INotificationRepository notificationRepository)
        {
            this.codeSmellRepository = codeSmellRepository;
            this.questionRepository = questionRepository;
            this.userManager = userManager;
            this.questionResponseRepository = questionResponseRepository;
            this.responseCommentRepository = responseCommentRepository;
            this.reportIssueRepository = reportIssueRepository;
            this.refactoringTechniqueRepository = refactoringTechniqueRepository;
            this.voteRepository = voteRepository;
            this._clientFactory = clientFactory;
            this.questionHub = questionHub;
            this.memoryCache = memoryCache;
            this.notificationRepository = notificationRepository;

        }
        public async Task<IActionResult> List(string? sortBy,
                                     string? questionType,
                                     string? filterType,
                                     int pageSize = 5,
                                     int pageNumber = 1)
        {
            var totalRecords = await questionRepository.CountAsync();
            var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

            if (pageNumber > totalPages)
            {
                pageNumber = (int)totalPages;
            }

            if (pageNumber < 1)
            {
                pageNumber = 1;
            }

            string? userId = null;
            if (!string.IsNullOrEmpty(filterType) && filterType == "MyQuestions")
            {
                //get the current user
                var user = await userManager.GetUserAsync(User);
                userId = user.Id;
            }

            IEnumerable<Question> questions = await questionRepository.GetAllAsync(sortBy, questionType, userId, pageNumber, pageSize);
            foreach (var question in questions)
            {
                question.Responses = (await questionResponseRepository.GetByQuestionId(question.Id)).ToList();
            }
            if (!string.IsNullOrEmpty(sortBy) && sortBy == "Responses")
            {
                questions = questions.OrderByDescending(q => q.Responses.Count()).ToList();
            }

            var viewModel = new QuestionListModel
            {
                Questions = questions,
                TotalPages = (int)totalPages,
                PageNumber = pageNumber,
                PageSize = pageSize,
                SortBy = sortBy,
                QuestionType = questionType,
                FilterType = filterType
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> PostQuestion()
        {
            var codeSmells = await codeSmellRepository.GetAllAsync();
            var model = new QuestionViewModel
            {
                CodeSmells = codeSmells.Select(cs => new SelectListItem
                {
                    Value = cs.Id.ToString(),
                    Text = cs.Name
                }).ToList()
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> PostQuestion(QuestionViewModel model)
        {
            var codeSmells = await codeSmellRepository.GetAllAsync();
            DateTime utcNow = DateTime.UtcNow;
            TimeZoneInfo malaysiaZone = TimeZoneInfo.FindSystemTimeZoneById("Singapore Standard Time");
            DateTime malaysiaTime = TimeZoneInfo.ConvertTimeFromUtc(utcNow, malaysiaZone);

            if (ModelState.IsValid)
            {
                var selectedCodeSmells = codeSmells.Where(cs => model.SelectedCodeSmellIds.Contains(cs.Id)).ToList();

                //get the current user
                var user = await userManager.GetUserAsync(User);

                var question = new Question
                {
                    Id = Guid.NewGuid(),
                    UserId = user.Id,
                    Title = model.Title,
                    Body = model.Body,
                    CodeSnippet = model.CodeSnippet,
                    PostedDate = malaysiaTime,
                    ModifiedDate = malaysiaTime,
                    Status = QuestionStatus.Open,
                    Type = model.Type,
                    IsDeleted = false,
                    CodeSmellList = selectedCodeSmells,
                    Images = model.ImageUrls.Where(url => !string.IsNullOrEmpty(url)).Select(url => new QuestionImage { ImageUrl = url }).ToList()
            };

                questionRepository.Add(question);
                TempData["success"] = "Question has been posted successfully";
                return RedirectToAction(nameof(List)); 
            }
            TempData["failure"] = "An issue in posting the question";
            model.CodeSmells = codeSmells.Select(cs => new SelectListItem
            {
                Value = cs.Id.ToString(),
                Text = cs.Name
            }).ToList();
            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var question = questionRepository.Get(id);
            var user = await userManager.GetUserAsync(User);
            if (question == null)
            {
                return NotFound();
            }

            var responses = (await questionResponseRepository.GetByQuestionId(id)).Select(r => new QuestionResponseViewModel
            {
                Id = r.Id,
                User = r.User,
                Body = r.Body,
                CodeSnippet = r.CodeSnippet,
                PostedDate = r.PostedDate,
                IsDeleted = r.IsDeleted,
                VoteCount = r.Votes.Count(v => v.IsUpvote) - r.Votes.Count(v => !v.IsUpvote),
                RefactoringTechniques = r.RefactoringTechniques.ToList(),
                CodeSmellList = r.CodeSmellList.ToList(),
                ResponseComments = responseCommentRepository.GetByResponseId(r.Id),
                VoteByUser = voteRepository.GetResponseVoteByUser(r.Id, user.Id)
             
            }).ToList();

            //create issue model
            CreateIssueViewModel createIssueModel = null;
            var claims = await userManager.GetClaimsAsync(user);
            var accessToken = claims.FirstOrDefault(c => c.Type == "access_token")?.Value;

            if (accessToken != null)
            {
                var client = _clientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                client.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("CoSmellRefine", "1.0"));

                var response = await client.GetStringAsync("https://api.github.com/user/repos");
                var repositories = JsonSerializer.Deserialize<List<Repository>>(response);

                if (repositories != null && repositories.Count > 0)
                {
                    var firstRepoFullName = repositories.First().full_name;
                    var owner = firstRepoFullName.Split('/')[0];

                    var repoSelectList = repositories.Select(repo => new SelectListItem
                    {
                        Value = repo.full_name,
                        Text = repo.name
                    }).ToList();

                    createIssueModel = new CreateIssueViewModel
                    {
                        Repo = repositories.First().full_name,
                        Owner = owner,
                        Repositories = repoSelectList
                    };
                }
            }


            var viewModel = new QuestionDetailViewModel
            {
                Question = question,
                Responses = responses,
                AddResponseComment = new AddResponseCommentViewModel(),
                AddReportIssue = new AddReportIssueViewModel(),
                AddResponse = new AddResponseViewModel
                {

CoSmellRefine/Views/DeveloperQuestion/List.cshtml
@model CoSmellRefine.Models.ViewModels.QuestionListModel


@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
    int nextPage = Model.PageNumber + 1;
    int prevPage = Model.PageNumber - 1;
}

<div class="container my-4">
    <div class="d-flex flex-row justify-content-between align-items-center">
        <div>
            <h2>All Questions</h2>
            <p>@Model.Questions.Count() questions</p>
        </div>
        <div>
            <a asp-controller="DeveloperQuestion" asp-action="PostQuestion" class="btn dark-btn">Ask Question</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <form method="get" asp-controller="DeveloperQuestion" asp-action="List">
                <div class="filter-section">
                    <h5>Filter by</h5>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="FilterType" value="All" id="allQuestions" checked>
                        <label class="form-check-label" for="allQuestions">
                            All questions
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="FilterType" value="MyQuestions" id="myQuestions">
                        <label class="form-check-label" for="myQuestions">
                            My questions
                        </label>
                    </div>

                    <h5 class="mt-4">Sorted by</h5>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="SortBy" value="Newest" id="newest" checked>
                        <label class="form-check-label" for="newest">
                            Newest
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="SortBy" value="Responses" id="responses">
                        <label class="form-check-label" for="responses">
                            Highest number of answers
                        </label>
                    </div>

                    <h5 class="mt-4">Question Type</h5>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="QuestionType" value="CodeSmellIdentification" id="codeSmellIdentification">
                        <label class="form-check-label" for="codeSmellIdentification">
                            Code Smell Identification
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" asp-for="QuestionType" value="RefactoringTechniqueIdentification" id="refactoringTechniqueIdentification">
                        <label class="form-check-label" for="refactoringTechniqueIdentification">
                            Refactoring Technique Identification
                        </label>
                    </div>
                    <div class="mt-2 d-flex justify-content-center align-items-center">
                        <button type="submit" class="btn light-btn btn-sm mt-2">
                            <i class="bi bi-funnel"></i> Apply filter
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-9">
            @foreach (var question in Model.Questions)
            {
                <a asp-controller="DeveloperQuestion" asp-action="Details" asp-route-id="@question.Id" class="question d-block" style="text-decoration: none; color: inherit;">
                    <div class="d-flex justify-content-between align-items-start mt-0 pt-0 mb-1">
                        @if (question.Status.Equals(CoSmellRefine.Utility.QuestionStatus.Open))
                        {
                            <span class="badge bg-success">@question.Status</span>
                        }
                        else
                        {
                            <span class="badge bg-danger">@question.Status</span>
                        }
                        @if (question.Type.Equals(CoSmellRefine.Utility.QuestionType.CodeSmellIdentification))
                        {
                            <span class="badge bg-primary">@question.Type</span>
                        }
                        else
                        {
                            <span class="badge bg-secondary">@question.Type</span>
                        }

                    </div>
                    <div class="d-flex justify-content-start">
                        <div style="width:15%;" class="d-flex flex-column justify-content-center align-items-center">
                            <p> @question.Responses.Count </p>
                            <p>@(question.Responses.Count>1 ? "answers" : "answer")</p>
                        </div>
                        <div class="d-flex justify-content-between w-75 position-relative">
                            <div>
                                <strong>@question.Title</strong>
                                <p>@question.Body</p>
                                <small class="text-muted">@question.User.UserName asked @question.PostedDate.ToShortTimeString()</small>
                            </div>
                  
                        </div>
                    </div>
                </a>
            }
        </div>
    </div>
    <nav aria-label="Page navigation example" class="bg-transparent mt-2 d-flex justify-content-center align-items-center">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link"
                    asp-controller="DeveloperQuestion"
                    asp-action="List"
                    asp-route-pageNumber="@prevPage"
                    asp-route-pageSize="@Model.PageSize"
                    asp-route-sortBy="@Model.SortBy"
                    asp-route-questionType="@Model.QuestionType"
                    asp-route-filterType="@Model.FilterType">
                    Previous
                </a>
            </li>

            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item">
                    <a class="page-link"
                        asp-controller="DeveloperQuestion"
                        asp-action="List"
                        asp-route-pageNumber="@i"
                        asp-route-pageSize="@Model.PageSize"
                        asp-route-sortBy="@Model.SortBy"
                        asp-route-questionType="@Model.QuestionType"
                        asp-route-filterType="@Model.FilterType">
                        @i
                    </a>
                </li>
            }

            <li class="page-item">
                <a class="page-link"
                    asp-controller="DeveloperQuestion"
                    asp-action="List"
                    asp-route-pageNumber="@nextPage"
                    asp-route-pageSize="@Model.PageSize"
                    asp-route-sortBy="@Model.SortBy"
                    asp-route-questionType="@Model.QuestionType"
                    asp-route-filterType="@Model.FilterType">
                    Next
                </a>
            </li>
        </ul>
    </nav>
</div>

CoSmellRefine/Views/DeveloperQuestion/PostQuestion.cshtml
@model CoSmellRefine.Models.ViewModels.QuestionViewModel
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    ViewData["Title"] = "CoSmellRefine";
}

<div class="container mt-5 h-100">
    <a asp-controller="DeveloperQuestion" asp-action="List" class="btn dark-btn mb-5">
        <i class="fas fa-arrow-left"></i> Back
    </a>
    <div class="progress question-progress mb-2" id="question-progressBar">
        <div class="progress-bar" id="question-progress" role="progressbar" style="width: 0%">0%</div>
    </div>
    <div id="questionForm" class="h-75">
        <form asp-action="PostQuestion" enctype="multipart/form-data" onsubmit="updateCodeSnippet()" class="h-100">
            <!-- Greeting Section -->
            <div id="greetingSection" class="question-form-section h-100">
                <div class="d-flex flex-column justify-content-center align-items-center h-100">
                    <p class="h1"> Hi there 👋<br>Let's ask a question</p>
                    <button type="button" class="btn light-btn mt-3" onclick="showNextSection('basicDetails', 20)"> Start </button>
                </div>
            </div>
            <!-- Basic Details Section -->
            <div id="basicDetails" class="question-form-section h-100">
                <div class="d-flex justify-content-between mb-4">
                    <button type="button" class="btn light-btn" onclick="showPreviousSection('greetingSection', 0)"> <i class="fas fa-arrow-left"></i> Back</button>
                    <button type="button" class="btn light-btn" onclick="showNextSection('codeSnippet', 40)">Continue <i class="fas fa-arrow-right"></i></button>
                </div>
                <p class="h2">Enter Your Question Details</p>
                <p>Provide a title and description to give context to your question</p>
                <div class="mb-3">
                    <label asp-for="Title" class="form-label"></label>
                    <input asp-for="Title" class="form-control" data-required="true" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label">Description</label>
                    <textarea asp-for="Body" class="form-control" data-required="true" ></textarea>
                    <span asp-validation-for="Body" class="text-danger"></span>
                </div>
            </div>

            <!-- Code Snippet Section -->
            <div id="codeSnippet" class="question-form-section">
                <div class="d-flex justify-content-between mb-4">
                    <button type="button" class="btn light-btn" onclick="showPreviousSection('basicDetails', 20)"> <i class="fas fa-arrow-left"></i> Back</button>
                    <button type="button" class="btn light-btn" onclick=" validateCodeSnippet()">Continue <i class="fas fa-arrow-right"></i></button>
                </div>
                <p class="h2">Paste Your Code Snippet</p>
                <p>Share the specific part of the code where you need help</p>
                <div id="editor" style="height: 200px;"></div>
                <textarea asp-for="CodeSnippet" id="codeSnippetText" hidden></textarea>
            </div>

            <!-- Upload Images Section -->
            <div id="uploadImages" class="question-form-section">
                <div class="d-flex justify-content-between mb-4">
                    <button type="button" class="btn light-btn" onclick="showPreviousSection('codeSnippet', 40)"><i class="fas fa-arrow-left"></i> Back</button>
                    <button type="button" class="btn light-btn" onclick="showNextSection('selection', 80)">Continue <i class="fas fa-arrow-right"></i></button>
                </div>
                <p class="h2">Upload Supporting Images</p>
                <p>Add images that help explain your code issue better.</p>
                <div class="dropzone question-dropzone" id="imageUploadDropzone"></div>
                <input asp-for="ImageUrls" type="hidden" id="imageUrls" />
            </div>

            <!-- Selection Section -->
            <div id="selection" class="question-form-section">
                <div class="d-flex justify-content-between mb-4">
                    <button type="button" class="btn dark-btn" onclick="showPreviousSection('uploadImages', 60)"> <i class="fas fa-arrow-left"></i> Back</button>
                    <button type="button" class="btn light-btn" onclick="showNextSection('additionalDetails', 80)">Continue <i class="fas fa-arrow-right"></i></button>
                </div>
                <p class="h2">Please Select an Option</p>
                <p>Choose whether your question is about identifying code smells or refactoring techniques</p>

                <div class="row d-flex justify-content-center">
                    <div class="col-12 col-md-3 d-flex flex-column justify-content-center align-items-center me-2 p-3 question-type-selection mt-3">
                        <input type="radio" asp-for="Type" id="CodeSmellIdentification" value="@CoSmellRefine.Utility.QuestionType.CodeSmellIdentification" data-required-radio="true" />
                        <label for="CodeSmellIdentification" class="d-flex justiy-content-center align-items-center flex-column mt-1">
                            <img src="/images/code_smell_identification.svg" alt="Code Smell Identification">
                            <p class="text-center m-2"> Code Smell Identification </p>
                        </label>
                    </div>
                    <div class="col-12 col-md-3 d-flex flex-column justify-content-center align-items-center me-2 p-3 question-type-selection mt-3">
                        <input type="radio" asp-for="Type" id="RefactoringTechniqueIdentification" value="@CoSmellRefine.Utility.QuestionType.RefactoringTechniqueIdentification" />
                        <label for="RefactoringTechniqueIdentification" class="d-flex justiy-content-center align-items-center flex-column mt-1">
                            <img src="/images/refactoring_technique_identification.svg" alt="Refactoring Technique Identification">
                            <p class="text-center m-2"> Refactoring Technique Identification </p>
                        </label>
                    </div>
                </div>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <!-- Additional Details Section -->
            <div id="additionalDetails" class="question-form-section">
                <div class="d-flex justify-content-between mb-4">
                    <button type="button" class="btn light-btn" onclick="showPreviousSection('selection', 80)"> <i class="fas fa-arrow-left"></i> Back</button>
                    <button type="button" class="btn light-btn" onclick="showNextSection('final', 100)">Continue <i class="fas fa-arrow-right"></i></button>
                </div>
                <p class="h2">Provide Additional Details</p>
                <p>Select the suspected code smells or the identified code smells.</p>
                <select asp-for="SelectedCodeSmellIds" class="form-control" id="additionalDetailsSelect" multiple="multiple" data-required-select="true" style="width: 100%;">
                    @foreach (var item in Model.CodeSmells)
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </select>
                <span asp-validation-for="SelectedCodeSmellIds" class="text-danger"></span>
            </div>
            <div id="final" class="question-form-section  h-100">
                <div class="d-flex justify-content-between mb-4">
                    <button type="button" class="btn dark-btn" onclick="showPreviousSection('additionalDetails', 80)"> <i class="fas fa-arrow-left"></i> Back</button>
                </div>
                <div class="d-flex flex-column justify-content-center align-items-center h-100">
                    <p class="h1"> 😄Alright, that's it!<br>Let's post the question.</p>
                    <button class="btn btn-success mt-3" type="submit"> Post Question </button>
                </div>
            </div>
        </form>
    </div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#additionalDetailsSelect').select2({
                placeholder: "Select additional details",
                allowClear: true
            });
        });

        function showNextSection(nextSectionId, progress) {
                // Check if the current section's required fields are filled
                var currentSection = $('.question-form-section:visible');
                var isValid = true;

                currentSection.find('[data-required="true"]').each(function () {
                    if ($(this).val().trim() === '') {
                        isValid = false;
                        $(this).addClass('is-invalid'); 
                    } else {
                        $(this).removeClass('is-invalid'); 
                    }
                });


                // Check for required radio buttons (Selection section)
                currentSection.find('[data-required-radio="true"]').each(function () {
                    if ($('input[name="' + $(this).attr('name') + '"]:checked').length === 0) {
                        isValid = false;
                        $(this).closest('.question-type-selection').addClass('is-invalid'); 
                    } else {
                        $(this).closest('.question-type-selection').removeClass('is-invalid'); 
                    }
                });

                // Check for required multi-select (Additional Details section)
                currentSection.find('[data-required-select="true"]').each(function () {
                    if ($(this).val().length === 0) {
                        isValid = false;
                        $(this).addClass('is-invalid'); // Highlight the field if needed
                    } else {
                        $(this).removeClass('is-invalid'); // Remove highlight if filled
                    }
                });

                if (!isValid) {
                    Swal.fire({
                        icon: 'warning',
                        title: 'Incomplete Fields',
                        text: 'Please fill out all required fields before proceeding.',
                    });
                    return;
                }

                // Hide current section and show next section
                $('.question-form-section').hide();
                $('#' + nextSectionId).show();
                $('#question-progress').css('width', progress + '%').text(progress + '%');
        }

        function showPreviousSection(prevSectionId, progress) {
            $('.question-form-section').hide();
            $('#' + prevSectionId).show();
            $('#question-progress').css('width', progress + '%').text(progress + '%');
        }


        showPreviousSection('greetingSection', 0);
        var editor = ace.edit("editor");
        editor.setTheme("ace/theme/github");
        editor.session.setMode("ace/mode/csharp");

        function validateCodeSnippet() {
            var codeSnippet = editor.getValue();

            if (codeSnippet.trim() === '') {
                Swal.fire({
                    icon: 'warning',
                    title: 'Empty Code Snippet',
                    text: 'Please enter a code snippet before proceeding.',
                });
                return;
            }

            $.ajax({
                url: '/api/CodeValidation/ValidateCSharp',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ CodeSnippet: codeSnippet }),
                success: function (response) {
                    showNextSection('uploadImages', 60);
                },
                error: function (xhr, status, error) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Invalid Code Snippet',
                        text: 'C# is the object-oriented language that is currently supported. Please enter a valid C# code snippet.',
                    });
                }
            });
        }

        function updateCodeSnippet() {
            var codeSnippet = editor.getValue();
            $('#codeSnippetText').val(codeSnippet);
        }

        var dropzone = new Dropzone("#imageUploadDropzone", {
            url: "/api/media",
            paramName: "file",
            maxFilesize: 2, // MB
            acceptedFiles: "image/*",
            uploadMultiple: false,
            init: function () {
                this.on("success", function (file, response) {
                    let imageUrlField = $('#imageUrls');
                    let existingUrls = imageUrlField.val() ? imageUrlField.val().split(',') : [];
                    existingUrls.push(response.link);
                    imageUrlField.val(existingUrls.join(','));
                });
                this.on("error", function (file, response) {
                    console.log("Failed to upload file:", response);
                });
            }
        });
    </script>
}